import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { JWTdecode } from "../src/JWTdecode";
import { Login } from "../src/components/Login";
import { Logout } from "../src/components/Logout";
import { RefreshSession } from "../src/components/RefreshSession";
import { Validate } from "../src/components/Validate";
import { JWTInfo } from "../src/components/JWTInfo";

const Home: NextPage = () => {
  const [session, setSession] = useState<string>(""); //JWT token
  const [refreshToken, setRefresh] = useState<string>(""); //Refresh token
  const [showRefreshTokenInfo, setShowRefreshTokenInfo] =
    useState<boolean>(false); //Show refresh token info
  const { payload } = session ? JWTdecode(session) : { payload: "" };

  return (
    <div>
      <Head>
        <title>JWT solo learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello {session ? payload.name : "guest"}!</h1>
        {!session && <Login setSession={setSession} setRefresh={setRefresh} />}
        {session && <Logout setSession={setSession} />}
        {session && <Validate token={session} />}

        {session && <RefreshSession
          token={session}
          refreshToken={refreshToken}
          setSession={setSession}
          setRefresh={setRefresh}
        />}
        {session && <JWTInfo token={session} />}
        { session && <h2>
          <input
            type="checkbox"
            checked={showRefreshTokenInfo}
            onChange={() => setShowRefreshTokenInfo(!showRefreshTokenInfo)}
          />
          Show refresh Token info{" "}
          {showRefreshTokenInfo ? <span>&#9650;</span> : <span>&#9660;</span>}
        </h2>}
        {session && showRefreshTokenInfo && (
          <JWTInfo token={refreshToken} name={"Refresh Token"} />
        )}
      </main>
      <br />
      <br />
      <footer>
        copyright &copy; {new Date().getFullYear()}{" "}
        <a href="///www.github.com/DiegoVallejoDev" target="blank">
          Diego Vallejo
        </a>
      </footer>
    </div>
  );
};

export default Home;
